version: '3.8'
services:
  crypto-pg:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crypto
      POSTGRES_PASSWORD: admin
    container_name: crypto_pg
  adminer:
    image: adminer
    ports:
      - "8088:8080"
  crypto-redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    image: com.dgazdag/crypto-recommender-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://crypto-pg:5432/crypto
    ports:
      - "8080:8080"
    depends_on:
      - crypto-pg
volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local