create table symbol_evaluation(
    id bigint primary key generated by default as identity not null,
    symbol varchar(8) not null,
    oldest_time timestamp not null,
    oldest_price double precision not null,
    newest_time timestamp not null,
    newest_price double precision not null,
    highest_time timestamp not null,
    highest_price double precision not null,
    lowest_time timestamp not null,
    lowest_price double precision not null,
    normalized_range double precision not null,
    dtype varchar(31) not null,
    date date
);

--create table symbol_price(
--    id bigint primary key generated by default as identity not null,
--    symbol_evaluation_id varchar(8) references symbol_evaluation(symbol),
--    time timestamp not null,
--    price double precision not null
--);
