openapi: 3.0.3
info:
  title: Crypto recommendation service
  version: 0.1.0
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: crypto
    description: Cryptos
paths:
  /cryptos:
    get:
      tags:
        - crypto
      summary: List all cryptos by descending order of normalized range
      description: List all cryptos
      operationId: getAll
      responses:
        '200':
          $ref: '#/components/responses/CryptoList'
        '429':
          $ref: '#/components/responses/Error'
        default:
          $ref: '#/components/responses/Error'
  /cryptos/{symbol}:
    get:
      tags:
        - crypto
      summary: Get details of a crypto
      description: Get details of a crypto
      operationId: getBySymbol
      parameters:
        - in: path
          name: symbol
          schema:
            type: string
          required: true
      responses:
        '200':
          $ref: '#/components/responses/Crypto'
        '404':
          $ref: '#/components/responses/Error'
        '429':
          $ref: '#/components/responses/Error'
        default:
          $ref: '#/components/responses/Error'
  /cryptos/highest:
    get:
      tags:
        - crypto
      summary: Returns the crypto with the highest normalized range for a specific day
      description: Returns the crypto with the highest normalized range
      operationId: getHighest
      parameters:
        - in: query
          name: localDate
          schema:
            type: string
            format: date
          required: true
      responses:
        '200':
          $ref: '#/components/responses/Crypto'
        '400':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '429':
          $ref: '#/components/responses/Error'
        default:
          $ref: '#/components/responses/Error'
components:
  schemas:
    Crypto:
      type: object
      properties:
        name:
          type: string
        normalizedRange:
          type: number
          format: double
        oldest:
          $ref: '#/components/schemas/CryptoPrice'
        newest:
          $ref: '#/components/schemas/CryptoPrice'
        max:
          $ref: '#/components/schemas/CryptoPrice'
        min:
          $ref: '#/components/schemas/CryptoPrice'
      required:
        - name
        - normalizedRange
        - oldest
        - newest
        - max
        - min
    CryptoPrice:
      type: object
      properties:
        date:
          type: string
          format: 'date-time'
        price:
          type: number
          format: double
    CryptoList:
      type: object
      properties:
        cryptos:
          type: array
          items:
            $ref: '#/components/schemas/Crypto'
    ApiError:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
  responses:
    Crypto:
      description: Single crypto
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Crypto'
    CryptoList:
      description: Crypto List in descending order of normalized range
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CryptoList'
    Error:
      description: Error occured
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
